server:
  port: 9999
spring:
  application:
    name: mybatisPlus
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/erp?useSSL=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:/top/mofeideyu/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true